/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.4.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    id 'java'
    id 'application'
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is found on compile classpath of this component and consumers.
    compileOnly 'javax.servlet:javax.servlet-api:3.1.0' 
    implementation 'commons-fileupload:commons-fileupload:1.4'
    implementation 'commons-io:commons-io:2.6'
    implementation 'org.apache.poi:poi:4.1.0'
    implementation 'log4j:log4j:1.2.17'
    implementation 'com.drewnoakes:metadata-extractor:2.12.0'
    implementation files('libs/java-image-scaling-0.8.6.jar')
    implementation files('libs/Filters.jar')

    // Use JUnit test framework
    testImplementation 'junit:junit:4.12'
}

mainClassName = 'pengguang.photoserver.Thumbnail'
